openapi: 3.0.1
info:
  title: Onebox ATM API
  version: v1
  contact:
    name: 'API Support contact'
    email: 'api-support@oneboxtds.com'
  x-logo:
    url: 'http://onebox-api-docs.s3.amazonaws.com/assets/img/logoob.svg'
servers:
  - url: 'https://api.oneboxtds.com'
    description: 'Production server'
  - url: 'https://api.oneboxtds.net'
    description: 'Test server'

tags:
  - name: Cart
    description: Cart
  - name:  Webhook
    description: Webhook
  - name: External email
    description: External email
  - name: Orders
    description: Orders
  - name: Users
    description: Users
  - name: Categories
    description: Categories
  - name: AVET
    description: Avet
  - name: Events
    description: Events
  - name: Price types
    description: Price types
  - name: Validate Member presale
    description: Validate Member presale
paths:
  /atm-api/v1/cart/register-football-member-discount:
    $ref: paths/register-football-members-discount.yml
  /atm-api/v1/cart/add-tour-member-ticket-and-promo:
    $ref: paths/add-tour-member-ticket-and-promo.yml
  /atm-api/v1/cart/add-football-friend-code-ticket-and-promo:
    $ref: paths/add-football-friend-code-ticket-promo.yml
  /atm-api/v1/cart/add-tour-friend-code-ticket-and-promo:
    $ref: paths/add-tour-friend-code-ticket-promo.yml
  /atm-api/v1/users/{tutorId}/related-users:
    $ref: paths/get-related-users.yml
  /atm-api/v1/users/{userSalesforceId}/promotions:
    $ref: paths/get-user-promotions.yml
  /atm-api/v1/users/{userSalesforceId}/add-promotion/{promotionId}:
    $ref: paths/add-promotion.yml
  /atm-api/v1/webhook:
    $ref: paths/webhook-notification.yml
  /atm-api/v1/orders/{orderCode}/send-external-email:
    $ref: paths/send-external-email.yml
  /atm-api/v1/orders/{orderCode}/tickets-url:
    $ref: paths/get-tickets-url.yml
  /atm-api/v1/categories:
    $ref: paths/get-categories.yml
  /atm-api/v1/avet-availability:
    $ref: paths/avet-availability.yml
  /atm-api/v1/events/{eventId}/sessions/{sessionId}/presale:
    $ref: paths/get-presale-information.yml
  /atm-api/v1/wizard/events/{eventId}/venue-templates/{venueTemplateId}/price-type-mappings:
    $ref: paths/set-up-price-type-codes.yml
  /atm-api/v1/users/{userSalesforceId}/presale/{sessionId}:
    $ref: paths/validate-member-presale.yml
