additionalProperties: false
type: object
required:
  - scope
properties:
  scope:
    $ref: ./notification-config-scope-enum.yml
  entity_id:
    type: integer
    format: int64
    description: Entity ID (Only required for user ROLE_OPR_MGR)
  channel_id:
    type: integer
    format: int64
    description: Channel ID (Only required when scope == CHANNEL)
  operator_id:
    type: integer
    format: int64
    description: Operator ID (Only required when is Super Operator)
  notification_url:
    type: string
  internal_name:
    type: string
  status:
    type: string
    enum:
      - ACTIVE
      - INACTIVE
  events:
    type: array
    items:
      $ref: ./event-actions-enum.yml