additionalProperties: false
type: object
required:
    - id    
properties:
  id:
    type: string
  scope:
    $ref: ./notification-config-scope-enum.yml
  status:
    $ref: ./notification-config-status-enum.yml
  visible:
    $ref: ./notification-config-visible-enum.yml
  operator:
    $ref: ../common/idname.yml
  entity:
    $ref: ../common/idname.yml
  channel:
    $ref: ../common/idname.yml
  notification_url:
    type: string
  api_key:
    type: string
  internal_name:
    type: string
  events:
    type: array
    items:
      $ref: ./event-actions-enum.yml