additionalProperties: false
type: object
properties:
  status:
    $ref: ./notification-config-status-enum.yml
  notification_url:
    type: string
  internal_name:
    type: string
  events:
    type: array
    items:
      $ref: ./event-actions-enum.yml