get:
  summary: Returns an object with event venue 3D views config
  description: ''
  tags:
    - Events
  parameters:
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
  responses:
    '200':
      description: A JSON with event venue 3D views config
      content:
        application/json:
          schema:
            $ref: '../../models/events/event-venue-view-config.yml'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml


put:
  summary: Save event config fields related to 3D venue views
  description: ''
  tags:
    - Events
  parameters:
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
  requestBody:
    description: Body
    required: true
    content:
      application/json:
        schema:
          $ref: '../../models/events/event-venue-view-config.yml'
  responses:
    '200':
      description: Saved successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

