type: array
required:
  - implementation
  - type
  - fields
  - operation_name
  - order_type
items:
  properties:
    operation_name:
      type: string
    implementation:
      type: string
    order_type:
      type: string
      enum:
        - BUY_SEAT
        - RENEWAL
        - CHANGE_SEAT
    type:
      type: string
      enum:
        - VALIDATION
        - INFERER
        - PRICE_CALCULATOR
        - DISCOUNT_CALCULATOR
    fields:
      type: array
      required:
        - id
        - type
        - container
      items:
        properties:
          id:
            type: string
          type:
            type: string
            enum:
              - INTEGER
              - STRING
          operation_name:
            type: string
          container:
            type: string
            enum:
              - LIST
              - SINGLE
              - MAP
              - METALIST
          source:
            type: string
            enum:
              - ROLE_ID
              - CAPACITY_ID
              - PERIODICITY_ID
              - TERM_ID
          target:
            type: string
            enum:
              - ROLE_ID
              - CAPACITY_ID
              - PERIODICITY_ID
              - TERM_ID
          value:
            type: array
            items:
              type: number