get:
  x-internal: true
  summary: Get avet restriction structure
  description: Get avet restriction structure
  security:
    - OAuth2: [ 'ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS' ]
  tags:
    - Member Config
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: eventId
      description: event id
      schema:
        type: number
      required: true
    - in: query
      name: restriction_type
      schema:
        type: string
        enum:
          - ROLE
          - PAYMENT
          - OBSERVATION
          - SECTOR_PASS
          - SESSION_START_TIME
      required: false
      description: Restriction type
  responses:
    '200':
      description: Get avet restriction structure
      content:
        application/json:
          schema:
            $ref: ../../models/avet-sector-restrictions/avet-sector-restrictions-structures.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
