openapi: 3.0.1
info:
  title: Onebox ATH API
  version: v1
  contact:
    name: 'API Support contact'
    email: 'api-support@oneboxtds.com'
  x-logo:
    url: 'http://onebox-api-docs.s3.amazonaws.com/assets/img/logoob.svg'
servers:
  - url: 'https://api.oneboxtds.com'
    description: 'Production server'
  - url: 'https://api.oneboxtds.net'
    description: 'Test server'

tags:
  - name: Free seat management
    description: Free seat management

paths:
  /ath-api/v1/login:
    $ref: paths/login.yml
  /ath-api/v1/release:
    $ref: paths/release.yml
  /ath-api/v1/recover:
    $ref: paths/recover.yml
  /ath-api/v1/transfers-list:
    $ref: paths/transfers-list.yml
