additionalProperties: false
type: object
properties:
  external_capacity_id:
    x-internal: true
    type: integer
    description: Capacity Id, only required when the type is AVET
  inventory_provider:
    x-internal: true
    type: string
    enum:
      - AVET
      - SGA
      - ONEBOX
      - SEETICKETS
  inventory_id:
    x-internal: true
    type: string