openapi: 3.0.1
info:
  title: Notifications API reference
  version: v1
  x-logo:
    url: 'http://onebox-api-docs.s3.amazonaws.com/assets/img/logoob.svg'
  description: Channels API reference
servers:
  - url: /ms-notification-api/v1
tags:
  - name: Webhook Configurations
paths:
  /webhooks:
    $ref: paths/webhooks/webhooks.yml
  /webhooks/{documentId}:
    $ref: paths/webhooks/webhook.yml
  /webhooks/{documentId}/apikey/regenerate:
    $ref: paths/webhooks/webhook-apikey-regenerate.yml