type: object
properties:
  venue3dId:
    type: string
    description: Venue 3D ID
  interactiveVenueType:
    $ref: ../common/interactive-venue-type.yml
  use3dVenueModule:
    type: boolean
    description: Allow 3D venue visualization
  use3dVenueModuleV2:
    type: boolean
    description: Allow 3D venue visualization for MMC
  useVenue3dView:
    type: boolean
    description: Allow 3D venue visualization
  useSector3dView:
    type: boolean
    description: Show 3D button on seat selection
  useSeat3dView:
    type: boolean
    description: Show 3D button on the cart summary