openapi: 3.0.1
info:
  title: Onebox ECI API
  version: v1
  contact:
    name: 'API Support contact'
    email: 'api-support@oneboxtds.com'
  x-logo:
    url: 'http://onebox-api-docs.s3.amazonaws.com/assets/img/logoob.svg'
servers:
  - url: 'https://api.oneboxtds.com'
    description: 'Production server'
  - url: 'https://api.oneboxtds.net'
    description: 'Test server'

tags:
  - name: Promotions
    description: Promotions
  - name:  Ticket-sales
    description: Sales

paths:
  /eci-api/v1/{channelId}/promotions:
    $ref: paths/promotions.yml
  /eci-api/v1/{channelId}/promotions/{promotionId}:
    $ref: paths/promotion.yml
  /eci-api/v1/{channelIdentifier}/ticket-sales:
    $ref: paths/channels-ticket-sales.yml
  /eci-api/v1/ticket-sales:
    $ref: paths/ticket-sales.yml
