get:
  summary: Get session external barcodes
  description: 'Get session external barcodes'
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - External Barcodes
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: eventId
      schema:
        type: integer
        format: int64
      required: true
      description: Event ID
    - in: path
      name: sessionId
      schema:
        type: integer
        format: int64
      required: true
      description: Session ID
  responses:
    '200':
      description: 'Session external barcodes config data'
      content:
        application/json:
          schema:
            $ref: ../../models/session/session-external-barcodes-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

put:
  summary: Update session external barcode config
  description: ''
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_OPR_MGR']
  tags:
    - External barcodes
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
    - in: path
      name: sessionId
      schema:
        type: integer
      required: true
      description: Session ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/session/session-external-barcodes-config.yml
  responses:
    '204':
      description: Saved successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml