get:
  summary: Get session external sessions config
  description: 'Get session external sessions config'
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Sessions
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: eventId
      schema:
        type: integer
        format: int64
      required: true
      description: Event ID
    - in: path
      name: sessionId
      schema:
        type: integer
        format: int64
      required: true
      description: Session ID
  responses:
    '200':
      description: 'Session external sessions config data'
      content:
        application/json:
          schema:
            $ref: ../../models/session/session-external-sessions-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
put:
  x-internal: true
  summary: Update session external sessions config
  description: 'Update session external sessions config'
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_OPR_MGR']
  tags:
    - Sessions
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
    - in: path
      name: sessionId
      schema:
        type: integer
      required: true
      description: Session ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            generalAdmission:
              type: boolean
              description: Enable joint sales
  responses:
    '204':
      description: Saved successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '412':
      description: Precondition Failed
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
