get:
  x-internal: true
  summary: Get session additional config
  description: Get session additional config
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Sessions
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: eventId
      schema:
        type: integer
        format: int64
      required: true
      description: Event ID
    - in: path
      name: sessionId
      schema:
        type: integer
        format: int64
      required: true
      description: Session ID
  responses:
    '200':
      description: A JSON with session additional configuration
      content:
        application/json:
          schema:
            $ref: ../../models/session/session-additional-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

