openapi: 3.0.1
info:
  title: Onebox Internal API
  version: v1
  contact:
    name: 'API Support contact'
    email: 'api-support@oneboxtds.com'
  x-logo:
    url: 'http://onebox-api-docs.s3.amazonaws.com/assets/img/logoob.svg'
servers:
  - url: 'https://api.oneboxtds.com'
    description: 'Production server'
  - url: 'https://api.oneboxtds.net'
    description: 'Test server'

tags:
  - name: Internal
    description: Internal
  - name: File management
    description: File management
  - name:  Automatic sales
    description: Automatic sales
  - name: SGTM Webhook
    description: Server-side Google Tag Manager webhook processing

paths:
  /internal-api/v1/automatic-sales/sessions/{sessionId}/sales:
    $ref: paths/sessions-sales.yml
  /internal-api/v1/automatic-sales/sessions/{sessionId}/file:
    $ref: paths/sessions-file.yml
  /internal-api/v1/automatic-sales/sessions/{sessionId}/file/exports:
    $ref: paths/sessions-file-export.yml
  /internal-api/v1/xml-sepa/generate:
    $ref: paths/generate.yml
  /internal-api/v1/sgtm/webhook:
    $ref: paths/sgtm-webhook.yml 