additionalProperties: false
type: object
properties:
      sessionSettings:
        type: object
        properties:
          showPriceFrom:
            type: boolean
      sessionSelection:
        type: object
        properties:
          type:
            type: string
            enum:
              - CALENDAR
              - LIST
          restrictType:
            type: boolean
          showAvailability:
            type: boolean
          calendar:
            $ref: 'whitelabel-settings-calendar.yml'
          list:
            $ref: 'whitelabel-settings-list.yml'
      seatSelection:
        type: object
        properties:
          changeSessionSelectType:
            type: string
            enum:
              - ALLOW
              - NONE
          showAvailability:
            type: boolean
          type:
            type: string
            enum:
              - CALENDAR
              - LIST
          restrictType:
              type: boolean
          calendar:
            $ref: 'whitelabel-settings-calendar.yml'
          list:
            $ref: 'whitelabel-settings-list.yml'