type: object
properties:
  sessionId:
    type: integer
    format: int64
    description: Session ID
  imageOrigin:
    type: string
    enum:
      - EVENT
      - CHANNEL_EVENT
      - SESSION
    description: | 
      Origin of the configured image.
      <table style="width:100%">
        <tr>
          <th>imageOrigin</th>
          <th>Description</th>
        </tr>
        <tr>
          <td>EVENT</th>
          <td>There are no square images configured</th>
        </tr>
        <tr>
          <td>CHANNEL_EVENT</th>
          <td>Square images are configured at event level</th>
        </tr>
        <tr>
          <td>SESSION</th>
          <td>Square images are configured at session level</th>
        </tr>
      </table>