type: object
properties:
  useEventDates:
    type: boolean
  releaseEnabled:
    type: boolean
  releaseDate:
    type: string
    format: date-time
  releaseDateTZ:
    type: string
  saleEnabled:
    type: boolean
  saleStartDate:
    type: string
    format: date-time
  saleStartDateTZ:
    type: string
  saleEndDate:
    type: string
    format: date-time
  saleEndDateTZ:
    type: string
  bookingEnabled:
    type: boolean
  bookingStartDate:
    type: string
    format: date-time
  bookingStartDateTZ:
    type: string
  bookingEndDate:
    type: string
    format: date-time
  bookingEndDateTZ:
    type: string
  secondaryMarketEnabled:
    type: boolean
  secondaryMarketStartDate:
    type: string
    format: date-time
  secondaryMarketStartDateTZ:
    type: string
  secondaryMarketEndDate:
    type: string
    format: date-time
  secondaryMarketEndDateTZ:
    type: string
