type: object
required:
  - enabled
properties:
  enabled:
    type: boolean
  vendor:
    $ref: event-accommodations-vendor.yml
  value:
    type: string
    example: 'https://closer2event.com/event=1a2b3c'
