type: object
properties:
  releaseSeatEnabled:
    type: boolean
  releaseSeatMaxDelayTime:
    type: integer
  recoverReleasedSeatMaxDelayTime:
    type: integer
  customerPercentage:
    type: number
  earningsLimit:
    $ref: ./season-ticket-release-seat-earnings-limit.yml
  excludedSessions:
    type: array
    items:
      type: integer
  maxReleases:
    type: integer
  maxReleasesEnabled:
    type: boolean