type: object
properties:
  type:
    type: string
    enum:
      - MONTHLY
      - WEEKLY
      - SLIDER
  calendarSelectType:
    type: string
    enum:
      - BY_HOUR
      - BY_LIST
  enabled:
    type: boolean