type: object
properties:
  redirectPolicy:
    type: object
    properties:
      mode:
        type: string
        description: Defines the mode for redirection.
        enum:
          - ORIGIN
          - CUSTOM
      url:
        type: object
        additionalProperties:
          type: string
        description: A map of redirection values with string keys and values.