openapi: 3.0.1
info:
  title: Onebox Fever API
  version: v1
  contact:
    name: 'API Support contact'
    email: 'api-support@oneboxtds.com'
  x-logo:
    url: 'http://onebox-api-docs.s3.amazonaws.com/assets/img/logoob.svg'
servers:
  - url: 'https://api.oneboxtds.com'
    description: 'Production server'
  - url: 'https://api.oneboxtds.net'
    description: 'Test server'

tags:
  - name: Webhook
    description: Webhook
  - name: Post Booking Questions
    description: Post Booking Questions
paths:
  /fever-api/v1/webhook:
    $ref: paths/webhook-notification.yml
  /fever-api/v1/external-reference:
    $ref: paths/external-reference.yml
  /fever-api/v1/post-booking-questions:
    $ref: paths/post-booking-questions.yml
  /fever-api/v1/entities/fv-zone:
    $ref: paths/entities.yml
  /fever-api/v1/user-auth:
    $ref: paths/user-auth.yml

