get:
  x-internal: true
  summary: Get product attribute values by product ID and attribute ID
  description: Get product attribute values by product id and attribute ID
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
    - in: path
      name: attributeId
      schema:
        type: integer
      required: true
      description: Product attribute ID
    - in: query
      name: limit
      description: The pagination limit
      schema:
        type: integer
      required: false
    - in: query
      name: offset
      description: The pagination offset
      schema:
        type: integer
      required: false
  responses:
    '200':
      description: Get list of product attribute value
      content:
        application/json:
          schema:
            $ref: ../../models/products/product-attribute-values.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

post:
  x-internal: true
  summary: Create product attribute value
  description: Create a new product attribute value
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: Product ID
    - in: path
      name: attributeId
      schema:
        type: integer
        format: int64
      required: true
      description: Product attribute ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/products/create-product-attribute-value.yml
  responses:
    '201':
      description: Product attribute value has been created successfully
      content:
        application/json:
          schema:
            additionalProperties: false
            type: object
            properties:
              id:
                type: integer
                format: int64
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
