get:
  summary: Get Sec-Mkt Event config
  description: Returns The Secondary Market Event Config in Couchbase
  tags:
    - Secondary Market Event Configs
  parameters:
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
  responses:
    '200':
      description: A JSON with event information
      content:
        application/json:
          schema:
            $ref: ../../models/sec-mkt/event-secondary-market-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Configuration not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

post:
  summary: Create Sec-Mkt Event config
  description: Create The Secondary Market Event Config in Couchbase
  tags:
    - Secondary Market Event Configs
  parameters:
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/sec-mkt/event-secondary-market-config.yml
  responses:
    '200':
      description: Saved successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Configuration not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

put:
  summary: Update Sec-Mkt Event config
  description: Update The Secondary Market Event Config in Couchbase
  tags:
    - Secondary Market Event Configs
  parameters:
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../models/sec-mkt/event-secondary-market-config.yml"

  responses:
    '200':
      description: Saved successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Configuration not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

delete:
  summary: Delete Sec-Mkt Event config
  description: Delete The Secondary Market Event Config from Couchbase
  tags:
    - Secondary Market Event Configs
  parameters:
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
  responses:
    '200':
      description: Saved successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Configuration not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
