get:
  summary: Get Sec-Mkt Sessions config
  description: Returns The Secondary Market Sessions Config in Couchbase
  tags:
    - Session Secondary Market Config
  parameters:
    - in: path
      name: sessionId
      schema:
        type: integer
      required: true
      description: Session ID
  responses:
    '200':
      description: A JSON with event information
      content:
        application/json:
          schema:
            $ref: ../../models/sec-mkt/session-secondary-market-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Configuration not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

post:
  summary: Create Sec-Mkt Session config
  description: Create The Secondary Market Session Config in Couchbase
  tags:
    - Session Secondary Market Config
  parameters:
    - in: path
      name: sessionId
      schema:
        type: integer
      required: true
      description: Session ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/sec-mkt/session-secondary-market-config.yml
  responses:
    '204':
      description: Saved successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Configuration not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

delete:
  summary: Delete Sec-Mkt Session config
  description: Delete The Secondary Market Session Config from Couchbase
  tags:
    - Session Secondary Market Config
  parameters:
    - in: path
      name: sessionId
      schema:
        type: integer
      required: true
      description: Session ID
  responses:
    '204':
      description: Saved successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Configuration not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
