additionalProperties: false
type: object
properties:
  expiration:
    type: object
    properties:
      enabled:
        type: boolean
      months:
        type: integer
  max_points:
    type: object
    properties:
      enabled:
        type: boolean
      amount:
        type: integer
  point_exchange:
    type: array
    items:
      type: object
      properties:
        code:
          type: string
        value:
          type: number
  last_reset:
    type: string
    format: date-time