additionalProperties: false
type: object
required:
  - channel_id
  - receipt_email
properties:
  filename:
    type: string
    description: Automatic sales filename
  sort:
    type: boolean
    description: Descending order of groups by size
  use_seat_mappings:
    type: boolean
    description: Sales by seat id
  use_ob_ids_for_seat_mappings:
    type: boolean
    description: Sales by OB seat id
  default_purchase_language:
    type: boolean
    description: If true, uses default channel language. If false, language has to be setted in body.
  skip_add_attendant:
    type: boolean
    description: Allow skip attendant data
  allow_break_adjacent_seats:
    type: boolean
    description: Allow break groups
  allow_skip_non_adjacent_seats:
    type: boolean
    description: Allow the script to continue running when non-adjacent seats are found for a group
  use_locators:
    type: boolean
    description: Allow to use related locators to a sale
  force_multi_ticket:
    type: boolean
    description: Allow send all season tickets
  channel_id:
    type: integer
    description: Channel id
  preview_token:
    type: string
    description: Preview token
  receipt_email:
    type: string
    description: Exports receipt email
  extra_field_value:
    type: string
    description: Indicate the attendant field to be mapped to the extra_field attribute
    enum:
      - ATTENDANT_NAME
      - ATTENDANT_SURNAME
      - ATTENDANT_ID_NUMBER
      - ATTENDANT_MEMBER_ID
      - ATTENDANT_MAIL
      - ATTENDANT_CELLPHONE
      - ATTENDANT_TOWN
      - ATTENDANT_PROVINCE
      - ATTENDANT_LICENSE_PLATE
      - ATTENDANT_CAR_MODEL
      - ATTENDANT_CHASSIS_NUMBER
      - ATTENDANT_RELEASE_DATE
      - ATTENDANT_COMPANY
      - ATTENDANT_JOB_TITLE
      - ATTENDANT_DATE_OF_BIRTH
      - ATTENDANT_NATIONALITY
      - ATTENDANT_GENDER
      - ATTENDANT_SHIRT_SIZE
      - ATTENDANT_LATERALITY
      - ATTENDANT_DISTANCE
      - ATTENDANT_CATEGORY
      - ATTENDANT_SUBCOUNTRY
      - ATTENDANT_NIF_NIE
      - ATTENDANT_SHIRT_SIZE_FAN_PACKAGE
      - ATTENDANT_FEEDING_TYPES
      - ATTENDANT_EXPIRATION_DATE
      - ATTENDANT_COUNTRY_OF_ISSUE
      - ATTENDANT_CAR_MODEL_NEW
      - ATTENDANT_CAR_BRAND
      - ATTENDANT_BUY_DATE