properties:
  host:
    description: The host of the skidata web service
    type: string
  port:
    description: The port of the skidata web service
    type: integer
  receiver:
    description: The receiver number as specified in the skidata documentation
    type: integer
  issuer:
    description: The issuer number as specified in the skidata documentation
    type: integer
  authorization_key:
    type: string