  additionalProperties: false
  type: object
  properties:
    multiple_purchase:
      type: boolean
      description: Indicates whether the member is allowed to purchase again the session during the pre-sale period, even if they have already completed a previous purchase. Only for Smart Booking sessions.
