additionalProperties: false
type: object
properties:
  avet_external_operative:
    type: boolean
  avet_match:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      match_date:
        type: string
        format: date-time
      start_sales_date:
        type: string
        format: date-time
      end_sales_date:
        type: string
        format: date-time
      match_date_confirmed:
        type: boolean