additionalProperties: false
type: object
properties:
  person_type:
    type: string
    description: Person type (digit 3). Each entity must define its own configuration of valid codes.
    nullable: false
  variable_code:
    type: string
    description: Variable code (digit 4). Each entity must define its own configuration of valid codes.
    nullable: false
  pass_type:
    type: string
    enum:
      - DAYS
      - USES
      - ALL_FAIR
      - PERIOD
    nullable: false
  uses:
    type: integer
    description: Number of uses if pass_type value is USES. Value between 1 and 10
    nullable: true
  days:
    type: integer
    description: Number of days if pass_type value is DAYS. Value between 1 and 10
    nullable: true
