additionalProperties: false
type: object
required:
  - entity_id
properties:
  inventory_provider:
    x-internal: true
    description: External inventory provider id
    type: string
    enum:
      - SGA
      - ONEBOX
  external_presale_id:
    type: string
    description: External sga presale Id only required when the inventory_provider is SGA
  entity_id:
    type: integer