additionalProperties: false
type: object
properties:
  enabled:
    type: boolean
  price:
    type: object
    properties:
      type:
        type: string
        enum:
          - PRICE_WITH_RESTRICTIONS
          - ORIGINAL_PRICE
          - UNRESTRICTED
          - PRORATED
      restrictions:
        type: object
        properties:
          min:
            type: number
            format: double
          max:
            type: number
            format: double
  commission:
    type: object
    properties:
      percentage:
        type: number
        format: double
  num_sessions:
    type: integer
  additional_settings:
    $ref: ../../models/season-ticket/season-tickets-secondary-market-additional-settings.yml
  sale_type:
    type: string
    enum:
      - FULL
      - PARTIAL
  customer_limits_enabled:
    type: boolean
  customer_limits:
    type: object
    properties:
      limit:
        type: number
      excluded_customer_types:
        type: array
        items:
          type: string