additionalProperties: false
type: object
properties:
  percentage:
    description: Percentage applied to a surcharge - Required if no fixed value is informed
    type: number
    example: 10.1
  fixed:
    description: Fixed amount applied to a surcharge - Required if no percentage value is informed
    type: number
    example: 1
  min:
    description: Minimum amount applied to a surcharge
    type: number
    example: 1.2
  max:
    description: Maximum amount applied to a surcharge
    type: number
    example: 5.2
