additionalProperties: false
type: object
properties:
  languages:
    type: object
    properties:
      default:
        type: string
        description: IETF language tag standard
        example: es-ES
      selected:
        type: array
        items:
          type: string
          description: IETF language tag standard
          example: es-ES
    description: Language configuration for the policy
