put:
  x-internal: true
  summary: Update member channel configuration info
  description: ''
  security:
    - OAuth2: ['ROLE_OPR_MGR', 'ROLE_CNL_MGR']
  tags:
    - Member Config
  parameters:
    -  in: header
       name: Authorization
       description: Bearer Token
       schema:
         type: string
       required: true
    -  in: path
       name: channelId
       schema:
         type: integer
         format: int64
       required: true
       description: Channel ID
    - in: path
      name: operationName
      schema:
        type: string
      required: true
      description: Operation Name
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../../models/channels/dynamic-configuration/channel-member-configuration-structure.yml
  responses:
    '200':
      description: Channel configuration updated successfully.
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error.yml
