openapi: 3.0.1
info:
  title: Onebox Palisis API
  version: v1
  contact:
    name: 'API Support contact'
    email: 'api-support@oneboxtds.com'
  x-logo:
    url: 'http://onebox-api-docs.s3.amazonaws.com/assets/img/logoob.svg'
servers:
  - url: 'https://api.oneboxtds.com'
    description: 'Production server'
  - url: 'https://api.oneboxtds.net'
    description: 'Test server'

tags:
  - name: Palisis
    description: Palisis

paths:
  /palisis-api/v1/entities/{entityId}/balance:
    $ref: paths/balance.yml
