type: object
description: Map of image settings by image type
additionalProperties:
  type: object
  description: 'property name is an image type. Valid types: ```SLIDER``` or ```HIGHLIGHTED```'
  properties:
    enabled:
      type: boolean
    images:
      type: object
      description: Map of images by language
      additionalProperties:
        type: array
        description: property name is a language
        items:
          type: object
          properties:
            image:
              type: string
              description: Image url
            thumbnail:
              type: string
              description: Image's thumbnail url
            position:
              type: number
            alt_text:
              type: string
              description: Image's alternative text
example:
  SLIDER:
    enabled: true
    images:
      en_EN:
        - image: '...0.png'
          thumbnail: '...0_thumbnail.png'
          position: 0
          alt_text: string
      es_ES:
        - image: '...0.png'
          thumbnail: '...0_thumbnail.png'
          position: 0
          alt_text: string
  HIGHLIGHTED:
    enabled: true
    images:
      en_EN:
        - image: '...0.png'
          alt_text: string
      es_ES:
        - image: '...0.png'
          alt_text: string
