type: object
description: Map of image settings by image type
additionalProperties:
  type: object
  description: 'property name is an image type. Valid types: ```SLIDER``` or ```HIGHLIGHTED```'
  properties:
    enabled:
      type: boolean
    images:
      type: object
      description: Map of images by language
      additionalProperties:
        type: array
        description: property name is a language
        items:
          type: object
          properties:
            image:
              type: string
              description: |
                Base64 binary of image with size constraints
                
                Expected specific size based on each type
                
                  <table style="width:100%">                    
                    <tr>
                      <th>Type</th>
                      <th>Dimensions</th>
                      <th>Maximum Size</th>
                    </tr>
                    <tr>
                      <td>SLIDER</th>
                      <td>1500x816px</th>
                      <td>200KB</th>
                    </tr>
                  </table>
            thumbnail:
              type: string
              description: |
                Base64 binary of image's thumbnail with size constraints
                
                Expected specific size based on each type
                
                  <table style="width:100%">                    
                    <tr>
                      <th>Type</th>
                      <th>Dimensions</th>
                      <th>Maximum Size</th>
                    </tr>
                    <tr>
                      <td>SLIDER</th>
                      <td>150s81px</th>
                      <td>35KB</th>
                    </tr>
                  </table>
            position:
              type: number
            alt_text:
              type: string
              description: Image's alternative text
example:
  SLIDER:
    enabled: true
    images:
      en_EN:
        - image: string
          thumbnail: string
          position: 0
          alt_text: string
      es_ES:
        - image: string
          thumbnail: string
          position: 0
          alt_text: string
  HIGHLIGHTED:
    enabled: true
    images:
      en_EN:
        - image: string
          alt_text: string
      es_ES:
        - image: string
          alt_text: string