additionalProperties: false
type: object
properties:
  free_seat:
    type: boolean
  show_update_partner_user:
    type: boolean
  member_enabled:
    type: boolean
  max_additional_members:
    type: number
  payment_renew_partner:
    type: integer
  emision_renew_partner:
    type: integer
  member_operation_periods:
    type: object
    additionalProperties:
      $ref: ./member-operation-period.yml
      description: Key-Value with key Period type and value with the information related to that period
      example:
        RENEWAL: ..
        CHANGE_SEAT: ..
  change_pin:
    type: boolean
  remember_pin:
    type: boolean
  blocked_matches:
    type: array
    items:
      type: number
  allow_free_seat_till:
    type: integer
  allow_recover_seat_till:
    type: integer
  prices_batch_enabled:
    type: boolean
  user_area:
    type: boolean
  new_member:
    type: boolean
  show_role:
    type: boolean
  show_subscription_mode:
    type: boolean
  show_previous_seat:
    type: boolean
  force_regenerate_passbook:
    type: boolean
  expiration_date_passbook:
    type: string
    format: date-time
  open_additional_members:
    type: boolean
  signup_email:
    type: boolean
  allow_cross_purchases:
    type: boolean
  allow_tutor_form:
    type: boolean
  tutee_max_age:
    type: number
  buy_url:
    type: string
  captcha_site_key:
    type: string
  captcha_enabled:
    type: boolean
  captcha_secret_key:
    type: string
  public_availability_enabled:
    type: boolean
  landing_button_url:
    type: string
  transfer_seat:
    type: boolean
  orphan_seats_enabled:
    type: object
    additionalProperties:
      type: boolean
      description: Key-Value with key Operation type and value with the charges amount
      example:
        RENEWAL: true
        CHANGE_SEAT: false
  download_passbook_permissions:
    type: array
    items:
      type: string
      enum:
        - NO_TICKETS
        - PENDING_APPROVAL
        - LEAVE
        - PENDING_ISSUE
        - ALLOWED_PASSAGE
        - DENIED_PASSAGE
    description: List of permissions that allow the member to download their passbook
  buy_seat_permission:
    type: string
    enum:
      - NO_TICKETS
      - PENDING_APPROVAL
      - LEAVE
      - PENDING_ISSUE
      - ALLOWED_PASSAGE
      - DENIED_PASSAGE
  new_member_permission:
    type: string
    enum:
      - NO_TICKETS
      - PENDING_APPROVAL
      - LEAVE
      - PENDING_ISSUE
      - ALLOWED_PASSAGE
      - DENIED_PASSAGE
  members_card_image:
    type: object
    properties:
      image:
        type: string
        description: Base64-encoded image binary