additionalProperties: false
type: object
properties:
  charges:
    type: object
    additionalProperties:
      type: number
      description: Key-Value with key Operation type and value with the charges amount
      example:
        RENEWAL: 2.0
        CHANGE_SEAT: 1.0
