get:
  summary: 'Event images configuration'
  description: 'Returns a list of sessions and their images configuration'
  tags:
    - Events
  parameters:
    - in: path
      name: eventId
      schema:
        type: integer
        format: int64
      required: true
      description: 'Event ID'
    - in: path
      name: channelId
      schema:
        type: integer
        format: int64
      required: true
      description: 'Channel ID'
  responses:
    '200':
      description: 'A list of sessions and its images origin'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../models/event/event-images-configuration.yml'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Configuration not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml