type: object
properties:
  validity_period:
    $ref: ./validity-period.yml
  installment_options:
    type: array
    description: Available installment options
    items:
      type: integer
    example: [ 3, 6, 12 ]
  custom_valid_period:
    type: boolean
    description: Whether the validity period is custom
  checkout_communication_elements:
    $ref: ./checkout-communication-elements.yml