openapi: 3.0.1
info:
  title: Onebox External Customer sync API
  version: v1
  contact:
    name: 'API Support contact'
    email: 'api-support@oneboxtds.com'
  x-logo:
    url: 'http://onebox-api-docs.s3.amazonaws.com/assets/img/logoob.svg'
servers:
  - url: 'https://api.oneboxtds.com'
    description: 'Production server'
  - url: 'https://gateway-pre.oneboxtickets.net'
    description: 'Test server'

tags:
  - name: Customer Sync
    description: Customer Sync

paths:
  /customer-sync-api/v1/customers/external-sync:
    $ref: paths/external-customer-sync.yml