get:
  summary: Get session config
  description: Get session config
  tags:
    - Sessions
  parameters:
    - in: path
      name: eventId
      schema:
        type: integer
        format: int64
      required: true
      description: Event ID
    - in: path
      name: sessionId
      schema:
        type: integer
        format: int64
      required: true
      description: Session ID
  responses:
    '200':
      description: A JSON session config data
      content:
        application/json:
          schema:
            $ref: ../../models/sessions/session-config.yml
    '400':
      description: Bad parameter
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: session not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
put:
  summary: Create or update session config
  description: Create or update session config
  tags:
    - Sessions
  parameters:
    - in: path
      name: eventId
      schema:
        type: integer
        format: int64
      required: true
      description: Event ID
    - in: path
      name: sessionId
      schema:
        type: integer
        format: int64
      required: true
      description: Session ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/sessions/session-config.yml
  responses:
    '204':
      description: Session config created or updated successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
