additionalProperties: false
type: object
properties:
  enabled:
    type: boolean
    description: Enable or disable ticket redemption functionality for the season ticket
  excluded_sessions:
    type: array
    items:
      type: integer
      format: int64
    description: List of session IDs that are excluded from redemption functionality
  expiration:
    $ref: ./redemption-expiration.yml
description: Configuration for season ticket redemption functionality