additionalProperties: false
type: object
description: Season ticket settings presales redirection policy
properties:
  mode:
    type: string
    description: Defines the mode for redirection.
    enum:
      - CATALOG
      - CUSTOM
  value:
    type: object
    additionalProperties:
      type: string
    description: A map of redirection values with string keys and values.