type: object
properties:
  enable_release_delay:
    type: boolean
  release_min_delay_time:
    type: integer
  release_max_delay_time:
    type: integer
  enable_recover_delay:
    type: boolean
  recover_max_delay_time:
    type: integer
  customer_percentage:
    type: number
  excluded_sessions:
    type: array
    items:
      type: integer
  max_releases:
    type: integer
  enable_max_releases:
    type: boolean
  earnings_limit:
    $ref: ./season-ticket-release-seat-earnings-limit.yml

