additionalProperties: false
type: object
description: Interactive venue settings
required:
  - allow_interactive_venue
properties:
  allow_interactive_venue:
    type: boolean
    description: Allow interactive venue for the event
  interactive_venue_type:
    description: Allowed virtual venue visualizations
    $ref: ../common/interactive-venue/interactive-venue-type.yml
  allow_venue_3d_view:
    type: boolean
    description: Allow 3D view on view selection
  allow_sector_3d_view:
    type: boolean
    description: Allow 3D view on sector selection
  allow_seat_3d_view:
    type: boolean
    description: Allow 3D view on the cart summary seat item
