additionalProperties: false
type: object
properties:
  venue_template_id:
    x-internal: true
    type: integer
    description: Venue template Id. Required if is SGA event type
  external_event_id:
    x-internal: true
    type: string
    description: External event Id.
  inventory_provider:
    x-internal: true
    description: External inventory provider id
    type: string
    enum:
      - SGA
      - ONEBOX
