additionalProperties: false
type: object
required:
  - languages
properties:
  languages:
    type: object
    required:
      - default
      - selected
    properties:
      default:
        type: string
        description: IETF language tag standard
        example: es-ES
      selected:
        type: array
        items:
          type: string
          description: IETF language tag standard
          example: es-ES
  operative:
    $ref: season-tickets-operative.yml
  bookings:
    $ref: ../event/event-settings-booking.yml
  subscription_list:
    type: object
    required:
      - enable
    properties:
      enable:
        type: boolean
      id:
        type: number
        format: integer
        description: Subscription list Id
  sales_goal:
    type: object
    properties:
      tickets:
        type: integer
      revenue:
        type: number
  categories:
    type: object
    properties:
      base:
        $ref: ../categories/category.yml
      custom:
        $ref: ../categories/category.yml
  tour:
    type: object
    properties:
      enable:
        type: boolean
        description: If enable, links season ticket to tour and tour_id must be defined
      id:
        type: integer
    description: If defined, links season ticket to corresponding tour
  use_producer_fiscal_data:
    type: boolean
  invitation_use_ticket_template:
    type: boolean
  interactive_venue:
    x-internal: true
    $ref: season-ticket-settings-interactive-venue.yml
  presales_redirection_policy:
    $ref: season-ticket-settings-presales-redirection-policy.yml
  simplified_invoice:
    x-internal: true
    type: object
    description: current settings for simplified invoice
    properties:
      id:
        type: integer
        description: the invoice prefix id
      producer_id:
        type: integer
        description: Producer ID
      prefix:
        type: string
        description: the simplified invoice prefix associated to this season ticket
      suffix:
        type: string
        description: the current numeration for the simplified invoice
