type: object
required:
  - benefits
properties:
  channel_id:
    type: integer
    format: int64
    description: Channel ID
  gateway_sid:
    type: string
    description: Gateway SID
  conf_sid:
    type: string
    description: Configuration SID
  event_id:
    type: integer
    format: int64
    description: Event ID
  benefits:
    type: array
    description: List of benefits
    items:
      $ref: ../../gateways/benefit-response.yml 