additionalProperties: false
type: object
properties:
  custom:
    type: boolean
  benefits:
    type: boolean
    description: Indicates if any gateway has benefits configured and active for this sale request
  channel_gateways:
    type: array
    items:
      $ref: '../channel-gateway.yml'