additionalProperties: false
type: object
properties:
  enabled:
    type: boolean
  published_seat_quota_id:
    type: number
  published_seat_price_type:
    type: array
    items:
      $ref: seat-price-type-request.yml