additionalProperties: false
type: object
properties:
  enabled:
    type: boolean
  published_seat_quota:
    $ref: ../common/idnamecode.yml
  published_seat_price_type:
    $ref: seat-price-type.yml
