additionalProperties: false
type: object
properties:
  ui_settings:
    type: object
    properties:
      session:
        type: object
        properties:
          show_price_from:
            type: boolean
      session_selection:
        type: object
        properties:
          type:
            type: string
            enum:
              - CALENDAR
              - LIST
          restrict_selection_type:
            type: boolean
          show_availability:
            type: boolean
          calendar:
            $ref: 'event-whitelabel-settings-calendar.yml'
          list:
            $ref: 'event-whitelabel-settings-list.yml'
      seat_selection:
        type: object
        properties:
          change_session:
            type: string
            enum:
              - ALLOW
              - NONE
          show_availability:
            type: boolean
          type:
            type: string
            enum:
              - CALENDAR
              - LIST
          restrict_selection_type:
            type: boolean
          calendar:
            $ref: 'event-whitelabel-settings-calendar.yml'
          list:
            $ref: 'event-whitelabel-settings-list.yml'