type: object
properties:
  catalog_design:
    type: object
    description: UI settings for the event catalog
    properties:
      list_view:
        description: Settings for the list view
        type: object
        properties:
          default:
            type: boolean
            example: false
          enabled:
            type: boolean
          image_config:
            type: string
            enum:
              - WITH_IMAGE
              - WITHOUT_IMAGE
      calendar_view:
        type: object
        description: Settings for the list view
        properties:
          default:
            type: boolean
            example: false
          enabled:
            type: boolean
          day_format:
            type: string
            enum:
              - MONTHLY
              - DAILY
          hour_format:
            type: string
            enum:
              - HOUR
              - LIST
          time_ranges:
            description: Group sessions date by Morning, Afternoon or Evening
            type: object
            properties:
              enabled:
                type: boolean
              Morning:
                $ref: event-catalog-ui-date-ranges.yml
              Afternoon:
                $ref: event-catalog-ui-date-ranges.yml
              Night:
                $ref: event-catalog-ui-date-ranges.yml
  session_config:
    type: object
    description: Sessions settings for both calendar and list views
    properties:
      show_session_availability:
        type: boolean
      show_session_from_prices:
        type: boolean
      show_calendar_in_ticket_selection:
        type: boolean