additionalProperties: false
type: object
properties:
  avet_config:
    x-internal: true
    $ref: event-avet-config-type.yml
    description: Avet Config, if is WS or Socket. Required if is AVET event type
  avet_competition_id:
    x-internal: true
    type: integer
    description: Avet Competition Id. Required if is AVET event type
  venue_template_id:
    x-internal: true
    type: integer
    description: Venue template Id. Required if is AVET event type
  external_event_id:
    x-internal: true
    type: string
    description: External event Id.
  standalone:
    x-internal: true
    type: boolean
    description: Is standalone event
  inventory_provider:
    x-internal: true
    description: External inventory provider id
    type: string
    enum:
      - AVET
      - SGA
      - ONEBOX
      - SEETICKETS
