additionalProperties: false
type: object
properties:
  use_event_dates:
    type: boolean
  release:
    type: object
    properties:
      enabled:
        type: boolean
      date:
        type: string
        format: date-time
  sale:
    type: object
    properties:
      enabled:
        type: boolean
      start_date:
        type: string
        format: date-time
      end_date:
        type: string
        format: date-time
  booking:
    type: object
    properties:
      enabled:
        type: boolean
      start_date:
        type: string
        format: date-time
      end_date:
        type: string
        format: date-time
  secondary_market_sale:
    type: object
    properties:
      enabled:
        type: boolean
      start_date:
        type: string
        format: date-time
      end_date:
        type: string
        format: date-time
  languages:
    type: object
    properties:
      default:
        type: string
      selected:
        type: array
        items:
          type: string