additionalProperties: false
type: object
required:
  - enable
properties:
  enable:
    type: boolean
    description: Allow changing seats
  event_change_seat_expiry:
    type: object
    description: amount time before the event start date time until the seat change is allowed. Example; 3 WEEK before the event starts.
    properties:
      time_offset_limit_amount:
        type: integer
      time_offset_limit_unit:
        type: string
        enum:
          - HOURS
          - DAYS
          - WEEKS
          - MONTHS
  change_type:
    type: string
    enum:
      - ALL
      - PARTIAL
  ticket_selection:
    type: object
    $ref: 'change-seat-event-ticket-selection.yml'
  reallocation_channel:
    type: object
    $ref: 'reallocation-channel.yml'