additionalProperties: false
type: object
properties:
  enabled:
    description: whether to enable or not an accommodations config for the event
    type: boolean
  vendor:
    description: the selected vendor for this event. Needs to be allowed by the entity
    $ref: ../common/accommodations-vendor.yml
  value:
    description: the base URL pointing to the vendor's dashboard for this particular event
    type: string
    example: 'https://www.closer2event.com?event=a1b2c3d4e5'
