additionalProperties: false
type: object
properties:
  allowed:
    type: boolean
    description: Enable the use of event external barcodes
  fair_code:
    type: string
    description: The event fair code (digits 1&2). Each entity must define its own configuration of valid codes.
  fair_edition:
    type: string
    description: The event fair edition code (digits 5&6). Each entity must define its own configuration of valid codes.
