type: object
properties:
  type:
    type: string
    enum:
      - MONTHLY
      - WEEKLY
  session_select:
    type: string
    enum:
      - BY_HOUR
      - BY_LIST
  enabled:
    type: boolean
    description: enable calendar settings