type: object
properties:
  contains_image:
    type: boolean
  media:
    type: string
    enum:
      - NONE
      - IMAGE
  card_design:
    type: string
    enum:
      - VERTICAL
      - HORIZONTAL
  enabled:
    type: boolean