additionalProperties: false
type: object
properties:
  sessionSelection:
    type: object
    properties:
      type:
        type: string
        enum:
          - CALENDAR
          - LIST
      restrictType:
        type: boolean
      showAvailability:
        type: boolean
      calendar:
        $ref: channel-pack-item-event-whitelabel-settings-calendar.yml
      list:
        $ref: channel-pack-item-event-whitelabel-settings-list.yml
  seatSelection:
    type: object
    properties:
      changeSessionSelectType:
        type: string
        enum:
          - ALLOW
          - NONE
      showAvailability:
        type: boolean
      type:
        type: string
        enum:
          - LIST
          - CALENDAR
      restrictType:
        type: boolean
      calendar:
        $ref: channel-pack-item-event-whitelabel-settings-calendar.yml
      list:
        $ref: channel-pack-item-event-whitelabel-settings-list.yml