additionalProperties: false
type: object
properties:
  containsImage:
    type: boolean
  media:
    type: string
    enum:
      - NONE
      - IMAGE
  cardDesignType:
    type: string
    enum:
      - VERTICAL
      - HORIZONTAL
  enabled:
    type: boolean