get:
  x-internal: true
  summary: Get channel reviews scope
  description: Get channel reviews scope
  security:
    - OAuth2: ['ROLE_CNL_MGR', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Channel Reviews
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: channelId
      schema:
        type: integer
      required: true
      description: Channel ID
    - in: query
      name: q
      schema:
        type: string
      description: Filter by session name and event name
    - in: query
      name: scope
      schema:
        type: string
      description: Filter by scope EVENT or SESSION
    - in: query
      name: offset
      schema:
        type: integer
      description: Offset (default 0)
    - in: query
      name: limit
      schema:
        type: integer
      description: Limit (default 10)
  responses:
    '200':
      description: 'List of customer types for the event'
      content:
        application/json:
          schema:
            $ref: "../../../models/channels/reviews/channel-review-scope-response.yml"
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error.yml
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../../models/common/error.yml
