get:
  x-internal: true
  summary: Get customers' authentication configuration
  description: ''
  security:
    - OAuth2: ['ROLE_OPR_MGR', 'ROLE_ENT_ADMIN', 'ROLE_CNL_MGR', 'ROLE_COL_MGR']
  tags:
    - Entities
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: entityId
      schema:
        type: integer
      required: true
  responses:
    '200':
      description: Customers' authentication configuration
      content:
        application/json:
          schema:
            $ref: ../../models/common/auth-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

put:
  x-internal: true
  summary: Update customers' authentication configuration
  description: ''
  security:
    - OAuth2: ['ROLE_OPR_MGR', 'ROLE_ENT_ADMIN', 'ROLE_CNL_MGR', 'ROLE_COL_MGR']
  tags:
    - Entities
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: entityId
      schema:
        type: integer
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/common/auth-config.yml
  responses:
    '204':
      description: Updated
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '412':
      description: Precondition failed
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml