get:
  x-internal: true
  summary: Get entity customer config
  description: Get all entity's customer config
  security:
    - OAuth2:
        - 'ROLE_CNL_MGR'
        - 'ROLE_EVN_MGR'
        - 'ROLE_ENT_ANS'
        - 'ROLE_OPR_MGR'
        - 'ROLE_OPR_ANS'
  tags:
    - Customers
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: entityId
      schema:
        type: integer
      required: true
      description: Entity ID
  responses:
    '200':
      description: Get entity customers config
      content:
        application/json:
          schema:
            $ref: ../../models/entities/customer-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

put:
  x-internal: true
  summary: Create or update entity customer config
  description: Creates or update customer config for an entity
  security:
    - OAuth2:
        - 'ROLE_OPR_MGR'
  tags:
    - Customers
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: entityId
      schema:
        type: integer
      required: true
      description: Entity ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/entities/customer-config.yml
  responses:
    '204':
      description: Customer Config updated successfully.
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
