get:
  x-internal: true
  summary: Get entity friends config
  security:
    - OAuth2:
        - 'ROLE_ENT_MGR'
        - 'ROLE_ENT_ANS'
        - 'ROLE_OPR_MGR'
        - 'ROLE_OPR_ANS'
  tags:
    - Customers
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: entityId
      schema:
        type: integer
      required: true
      description: Entity ID
  responses:
    '200':
      description: Get entity friends config
      content:
        application/json:
          schema:
            $ref: ../../models/entities/friends-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

put:
  x-internal: true
  summary: Update entity friends config
  description: Update entity friends config
  security:
    - OAuth2:
        - 'ROLE_ENT_MGR'
        - 'ROLE_OPR_MGR'
  tags:
    - Customers
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: entityId
      schema:
        type: integer
      required: true
      description: Entity ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/entities/friends-config-update.yml
  responses:
    '204':
      description: Friends config updated successfully.
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
