get:
  x-internal: true
  summary: Get entity gateways config
  description: Get entity gateways config
  security:
    - OAuth2: ['ROLE_CNL_TAQ']
  tags:
    - Entities
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: entityId
      schema:
        type: integer
      required: true
      description: Entity ID
  responses:
    '200':
      description: Array of gateways config
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../../models/entities/gateway-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml