type: object
description: Configuration for booking checkout redirection
properties:
  enabled:
    type: boolean
    description: Enables or disables the booking checkout feature
  channel_id:
    type: integer
    format: int64
    description: ID of the channel where the final customer will complete the purchase
  channel_name:
    type: string
    description: Name of the checkout channel (auto-filled based on the ID)
  payment_settings:
    type: array
    description: Payment settings for B2B booking checkout
    items:
      type: object
      properties:
        default:
          type: boolean
          description: Is the default payment method for B2B
        active:
          type: boolean
          description: Is this payment method active for B2B booking checkout
        gateway_sid:
          type: string
          description: Gateway SID
        conf_sid:
          type: string
          description: Configuration SID