type: array
items:
  type: object
  properties:
    mode:
      $ref: channel-purchase-config-link-destination-mode.yml
    type:
      $ref: channel-purchase-config-link-destination-type.yml
    value:
      type: object
      additionalProperties:
        type: string
      description: Key-Value with key IETF language tag standard and value with the url
      example:
        en-US: "https://redirect-site.org"
        es-ES: "https://redirect-site.org"