additionalProperties: false
type: object
properties:
  taxes:
    description: |
      Defines how taxes are displayed in the channel.
      - `INCLUDED`: Taxes are included in the price and not shown separately.
      - `INCLUDED_ITEMIZED`: Taxes are included in the price but shown separately.
      - `ON_TOP`: Taxes are added on top of the price and shown separately.
    type: string
    enum:
      - INCLUDED
      - INCLUDED_ITEMIZED
      - ON_TOP
  prices:
    description: |
      Defines how the prices are displayed in the channel.
      - `NET`: Prices are shown without taxes. Only available for channels with `taxes.display_mode` set to `ON_TOP`.
      - `BASE`: Prices are shown with base price
      - `FINAL`: Prices are shown with all applicable surcharges included.
    type: string
    enum:
      - NET
      - BASE
      - FINAL