additionalProperties: false
type: object
properties:
  allow_booking:
    type: boolean
    description: Allow bookings for the channel
  allow_booking_checkout:
    type: boolean
    description: Allow bookings checkout for the channel
  booking_checkout_domain:
    type: string
    description: The domain used to compose the booking checkout url
  booking_checkout_payment_methods:
    type: array
    items:
      type: string
    description: Payment methods for the booking checkout feature (Payment method must be active in channel)
  allow_customer_assignation:
    type: boolean
    description: Allow customer assignation for the channel
  allow_presale_restrictions:
    type: boolean
    description: Allow applying presale restrictions to reservations
