additionalProperties: false
type: object
properties:
  promotions:
    type: object
    properties:
      locations:
        type: array
        items:
          type: string
          enum:
            - SEAT_SELECTION_DIALOG
            - SEAT_SELECTION_REQUIRED_DIALOG
      application_config:
        type: string
        enum:
          - AUTO
          - DEFAULT
  venue_map:
    type: object
    properties:
      navigation_mode:
        type: string
        enum:
          - VIEWS
          - PRICE_ZONES
      show_available_tickets:
        type: boolean
      allow_price_range_filter:
        type: boolean
      show_images_carousel:
        type: boolean
      preselected_items:
        type: integer
      show_compacted_view_list:
        type: boolean
      force_side_panel_view_list:
        type: boolean
  thank_you_page:
    type: object
    properties:
      show_purchase_conditions:
        type: boolean
      modules:
        type: array
        items:
          type: object
          properties:
            text_block_id:
              type: number
            enabled:
              type: boolean
            visible:
              type: boolean
  cart:
    type: object
    properties:
      allow_keep_buying:
        type: boolean
  reviews:
    type: object
    properties:
      enabled:
        type: boolean
  checkout:
    type: object
    properties:
      checkout_flow:
        type: string
        enum:
          - ONE_STEP
          - TWO_STEP
      attendees:
        type: object
        properties:
          autofill:
            type: boolean
  resend_tickets:
    type: object
    properties:
      enabled:
        type: boolean