additionalProperties: false
type: object
properties:
  visualization:
    $ref: channel-purchase-config-sessions-visualization.yml
  promotions:
    type: object
    properties:
      code_persistence:
        $ref: channel-promotions-code-persistence.yml