additionalProperties: false
type: object
properties:
  allow_interactive_venue:
    type: boolean
  interactive_venue_types:
    type: array
    items:
      $ref: ../common/interactive-venue/interactive-venue-type.yml
  allow_venue_3d_view:
    type: boolean
  allow_sector_3d_view:
    type: boolean
  allow_seat_3d_view:
    type: boolean
  content_layout:
    $ref: channel-content-venue-layout.yml