additionalProperties: false
type: object
required:
  - server
  - port
  - security
  - user
  - password
  - require_auth
properties:
  server:
    type: string
    nullable: false
  port:
    type: number
    nullable: false
  user:
    type: string
    nullable: true
  password:
    type: string
    nullable: true
  security:
    type: string
    enum:
      - NONE
      - STARTTLS
      - SSL_TLS
    nullable: false
  require_auth:
    type: boolean
    nullable: false
