additionalProperties: false
type: object
properties:
  include_taxes_separately:
    type: boolean
    deprecated: true
  buyer_registration:
    $ref: channel-buyer-registration.yml
  commercial_information_consent:
    $ref: commercial-information-consent.yml
  venue:
    $ref: channel-purchase-config-venues.yml
  sessions:
    $ref: channel-purchase-config-sessions.yml
  header_texts:
    type: array
    items:
      $ref: channel-purchase-config-header-text.yml
  redirection_policy:
    $ref: channel-purchase-config-redirection-policy.yml
  show_accept_all_option:
    type: boolean
  add_related_channel:
    type: boolean
  related_channel:
    type: integer
  invoice:
    $ref: channel-purchase-config-invoice.yml
  loyalty_program:
    $ref: channel-purchase-config-loyalty-program.yml
  price_display:
    $ref: channel-purchase-config-price-display.yml
  allow_price_type_tag_filter:
    type: boolean