additionalProperties: false
type: object
required:
  - calculation
description: Surcharges settings
properties:
  calculation:
    type: string
    enum:
      - BEFORE_CHANNEL_PROMOTIONS
      - AFTER_CHANNEL_PROMOTIONS
    description: Surcharges calculation