additionalProperties: false
type: object
properties:
  reception:
    type: object
    properties:
      type:
        type: string
        enum:
          - SESSION_START
          - PURCHASE
      hours:
        type: integer