type: object
description: Settings for channel invitations (Channel's entity must allow invitations)
properties:
  enabled:
    type: boolean
  selection_mode:
    type: string
    description: |
      <ul>
        <li><b>AUTO:</b> All tickets are invitations
        <li><b>MANUAL_ALL:</b> The invitations will be selected manually and all tickets are marked as invitations by default
        <li><b>MANUAL_NONE:</b> The invitations will be selected manually and no tickets are marked as invitations by default
      </ul>
    enum:
      - AUTO
      - MANUAL_ALL
      - MANUAL_NONE