additionalProperties: false
type: object
properties:
  enabled:
    type: boolean
  mandatory_thresholds:
    type: array
    items:
      $ref: channel-purchase-config-mandatory-threshold.yml
  invoice_generation_mode:
    $ref: channel-invoice-generation-mode.yml
  invoice_request_type:
    $ref: channel-invoice-request-type.yml