additionalProperties: false
type: object
required:
  - surcharges
  - use_multi_event
  - allow_data_protection_fields
  - allow_linked_customers
properties:
  automatic_seat_selection:
    type: boolean
  automatic_seat_selection_by_price_zone:
    type: boolean
  enable_b2b:
    type: boolean
  surcharges:
    $ref: channel-settings-surcharges.yml
  use_multi_event:
    type: boolean
  allow_data_protection_fields:
    type: boolean
    description: Only for 'BOX_OFFICE' channel type
  allow_linked_customers:
    type: boolean
    description: Only for 'WEB' channel type. Allows customers to link accounts.
  use_robot_indexation:
    type: boolean
    description: Enables search engine indexation in portal.
  robots_no_follow:
    type: boolean
    description: Disable search engine indexation in portal (actual).
  v4_enabled:
    type: boolean
    description: Enable functionalities of portal v4.
  v4_config_enabled:
    type: boolean
    description: Enable functionalities of portal v4.
  v2_receipt_template_enabled:
    type: boolean
    description: Enable v2 receipt template
  allow_download_passbook:
    type: boolean
    description: Enable the download of the passbook for portal v4.
  allow_B2B_publishing:
    type: boolean
    description: Enables B2B Seat Publishing. Only for 'WEB_B2B' channel type whose entity allows such config
  enable_B2B_event_category_filter:
    type: boolean
    description: Enables B2B events category filter. Only for 'PORTAL_B2B' channels
  invitations:
    $ref: channel-settings-invitations.yml
  support_email:
    $ref: support-email.yml
  donations:
    $ref: donations-config.yml
  whatsapp:
    $ref: whatsapp-templates-config.yml
  active_promotion:
    type: boolean
  use_currency_exchange:
    x-internal: true
    type: boolean
  currency_default_exchange:
    x-internal: true
    type: string
  customer_assignation:
    $ref: channel-customer-assignation.yml
  enable_packs_and_events_catalog:
    type: boolean