additionalProperties: false
type: object
properties:
  domain_fallback:
    type: object
    properties:
      enabled:
        type: boolean
      channels_allowed:
        type: string
        enum:
          - ALL
          - RESTRICTED
      rules:
        type: array
        items:
          type: object
          properties:
            values:
              type: array
              items:
                type: string
            type:
              type: string
              enum:
                - STARTS_WITH
                - ENDS_WITH
                - CONTAINS
                - IS
      default_redirection_url:
        type: string
  social_login:
    type: object
    properties:
      google_client_id:
        type: string