type: object
x-internal: true
properties:
  enabled:
    type: boolean
    description: Indicates whether donations are enabled.
  provider:
    type: object
    description: Information about the donation provider.
    properties:
      id:
        type: integer
        description: Unique identifier for the provider.
      target_id:
        type: string
        description: Identifier for the target of the donations.
      additional_properties:
        type: array
        items:
          type: object
        description: Additional properties defined for the provider. Each object in the array can contain properties with any type of value, mimicking the flexibility of a Map<String, Object>.
  settings:
    type: object
    description: Specific settings for the donation.
    properties:
      type:
        type: string
        enum:
          - ROUND_UP
          - UNRESTRICTED
          - CUSTOM
        description: Type of donation.
      amount:
        type: number
        description: Donation amount.
      options:
        type: array
        items:
          type: number
        description: Additional configuration to set a list of predefined donation amounts.
  campaign:
    type: object
    description: Specific info for the campaign.
    properties:
      id:
        type: string
      name:
          type: string
      foundation:
        type: string
      currency_code:
        type: string
      website:
        type: string