type: object
properties:
  scope:
    $ref: ./notification-config-scope-enum.yml
  status:
    $ref: ./notification-config-status-enum.yml
  visible:
    $ref: ./notification-config-visible-enum.yml
  operatorId:
    type: integer
  entityId:
    type: integer
  channelId:
    type: integer
  url:
    type: string
  internalName:
    type: string
  events:
    type: object
    description: Map of events and their actions
    additionalProperties:
      type: array
      items:
        type: string
    example:
      ORDER: [PURCHASE, BOOKING]
      ITEM: PURCHASE