additionalProperties: false
type: object
properties:
  enabled:
    type: boolean
  use_entity_config:
    type: boolean
  max_members:
    $ref: ./max-members.yml
  authenticators:
    $ref: ./authenticators.yml
  settings:
    $ref: ./portal_settings.yml
