additionalProperties: false
type: object
properties:
  mode:
    type: string
    enum:
      - REQUIRED
      - NON_REQUIRED
  blocked_customer_types_enabled:
    type: boolean
  blocked_customer_types:
    type: array
    items:
      type: string
  triggers_on:
    type: array
    items:
      type: string
      enum:
        - IMMEDIATELY
        - BEFORE_CHECKOUT
        - BEFORE_SELECT_LOCATION
  user_data_editable:
    type: boolean
  account_creation:
    type: string
    enum:
      - ENABLED
      - DISABLED
  phone_validator:
    type: object
    properties:
      enabled:
        type: boolean
      validator_id:
        type: string
      available_validators:
        type: array
        items:
          type: string
