get:
  x-internal: true
  summary: Get channel purchase config
  description: 'Retrieves the channel purchase config'
  security:
    - OAuth2: ['ROLE_CNL_MGR', 'ROLE_OPR_MGR']
  tags:
    - Purchase Config
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: channelId
      schema:
        type: integer
        format: int64
      required: true
      description: Channel ID
  responses:
    '200':
      description: 'Successful response'
      content:
        application/json:
          schema:
            $ref: ../../models/channels/channel-purchase-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '405':
      description: Method not allowed
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
put:
  x-internal: true
  summary: Update the channel purchase config
  description: 'Updates the channel purchase config'
  security:
    - OAuth2: ['ROLE_CNL_MGR', 'ROLE_OPR_MGR']
  tags:
    - Purchase Config
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: channelId
      schema:
        type: integer
        format: int64
      required: true
      description: Channel ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/channels/channel-purchase-config.yml
  responses:
    '204':
      description: Fields updated
    '400':
      description: bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: invalid token
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml