get:
  x-internal: true
  summary: Get channel whitelabel settings
  description: Get channel whitelabel settings by ID
  security:
    - OAuth2: ['ROLE_CNL_MGR', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Channels
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: channelId
      schema:
        type: integer
      required: true
      description: Channel ID
  responses:
    '200':
      description: Get channel whitelabel settings
      content:
        application/json:
          schema:
            $ref: ../../models/channels/channel-whitelabel-settings.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
put:
  x-internal: true
  summary: Update channel whitelabel settings
  description: Update channel whitelabel settings
  security:
    - OAuth2:
        - 'ROLE_CNL_MGR'
        - 'ROLE_OPR_MGR'
  tags:
    - Channels
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: channelId
      schema:
        type: integer
      required: true
      description: Channel ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/channels/channel-whitelabel-settings-update.yml
  responses:
    '204':
      description: Channel whitelabel settings updated successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
