additionalProperties: false
type: object
required:
  - enabled
properties:
  enabled:
    description: whether to enable or not accommodations for the entity and its channels
    type: boolean
  allowed_vendors:
    description: list of allowed accommodations vendors
    type: array
    items:
      $ref: ../common/accommodations-vendor.yml
  channel_enabling_mode:
    description: the way an enabled entity will cascade to its channels
    $ref: accommodations-channel-enabling-mode.yml
  enabled_channels:
    description: list of channels that will be enabled in cascade with the entity (only applies when enabling mode is RESTRICTED)
    type: array
    items:
      type: integer
      format: int64