additionalProperties: false
type: object
properties:
  enabled:
    type: boolean
  logo_url:
    type: string
    description: URL where logo_url resources are located
  tiny_url:
    type: string
    description: URL where tiny_url resources are located
  favicon_url:
      type: string
      description: URL where favicon_url resources are located