get:
  x-internal: true
  summary: Get season ticket secondary market config
  description: Get a season ticket secondary market config by id
  security:
    - OAuth2:
        - 'ROLE_EVN_MGR'
        - 'ROLE_OPR_MGR'
        - 'ROLE_ENT_ANS'
        - 'ROLE_OPR_ANS'
  tags:
    - Secondary Market Config
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
  responses:
    '200':
      description: Get season ticket secondary market config
      content:
        application/json:
          schema:
            $ref: ../../models/secondary-market/season-tickets-secondary-market-config.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

post:
  x-internal: true
  summary: Set season ticket secondary market config
  security:
    - OAuth2:
        - 'ROLE_EVN_MGR'
        - 'ROLE_OPR_MGR'
        - 'ROLE_ENT_ANS'
        - 'ROLE_OPR_ANS'
  tags:
    - Secondary Market Config
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/secondary-market/season-tickets-secondary-market-config.yml
  responses:
    '204':
      description: Season ticket secondary market config added successfully.
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml