get:
  x-internal: true
  summary: Get session secondary market config
  description: Get a session secondary market config by id
  security:
    - OAuth2:
        - 'ROLE_EVN_MGR'
        - 'ROLE_OPR_MGR'
        - 'ROLE_ENT_ANS'
        - 'ROLE_OPR_ANS'
  tags:
    - Secondary Market Config
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: sessionId
      schema:
        type: integer
      required: true
      description: Session ID
  responses:
    '200':
      description: Get session secondary market config
      content:
        application/json:
          schema:
            $ref: '../../models/secondary-market/session-secondary-market-config.yml'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
post:
  x-internal: true
  summary: Set session secondary market config
  security:
    - OAuth2:
        - 'ROLE_EVN_MGR'
        - 'ROLE_OPR_MGR'
        - 'ROLE_ENT_ANS'
        - 'ROLE_OPR_ANS'
  tags:
    - Secondary Market Config
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: sessionId
      schema:
        type: integer
      required: true
      description: Session ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../models/secondary-market/session-secondary-market-config.yml'
  responses:
    '204':
      description: Session secondary market config added successfuly.
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
delete:
  x-internal: true
  summary: Delete session secondary market config
  description: Delete a session secondary market config by id
  security:
    - OAuth2:
        - 'ROLE_EVN_MGR'
        - 'ROLE_OPR_MGR'
        - 'ROLE_ENT_ANS'
        - 'ROLE_OPR_ANS'
  tags:
    - Secondary Market Config
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: sessionId
      schema:
        type: integer
      required: true
      description: Session ID
  responses:
    '204':
      description: Delete session secondary market config
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
