type: object
properties:
  show_date:
    description: The pack will display the date only using Date format
    type: boolean
  show_date_time:
    description:  The pack will display the date using Date Time format
    type: boolean
  show_main_venue:
    description: The pack will use the main item's venue to be displayed
    type: boolean
  show_main_date:
    description: The pack will use the main item's date to be displayed
    type: boolean